name = "Shidpack"
author = "ri0tjuice"
version = "1.0.1dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e7f0d9dc33689a0fb29fb57917f2dd36047ebe8ea7938c8a0bba88ee989e824"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
