name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95b45e8ead430ac56dfa81d7235e21d708bb4b67aef9980097f1152ec570521b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
