name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d420e4710fa5ffa95c45e20c7260c3f5c7f46928c3c5c2ef8a156cfc021860d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
