name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66b0c70895aeaadda8d98755965428be0248ac89cacadd69091dcb1746ecf3fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
