name = "Shidpack"
author = "ri0tjuice"
version = "1.0.2dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eab404ff75ad883051510f68dae469383d09d4b65ec20ea9ced368966f12444"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
