name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8830b9557f2fb074ea2101339ef77456fd8b0feb83d029074458f34149bac127"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
