name = "Shidpack"
author = "ri0tjuice"
version = "1.0.1dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "428cf1c2954f8c62501ab06277ab041647ac908ace63136f89002c1eda93c2de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
