name = "Shidpack"
author = "ri0tjuice"
version = "1.0.3dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9b13f64d8018c71a4ba9a9be6bca39a59953747226738b188a4d9e21b255ca8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
