name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55c2a78be447db1f334db6fc1adc058d194738809c5af09069c6be0ebd968fe4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
