name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19b79be9c5d156a2f4871fbdd93f5c40e0d8ddc1b8cc1b28956a410cb3aa2781"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
