name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a106feee1755a186766ab1b360be3fcbec1f88523b3454a5ab4682be6affa789"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
