name = "Shidpack"
author = "ri0tjuice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa01881bf1b914e0d8314254399b7b9a4882ccb39fc585ad148cdc07b66be71e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
